/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tooparking;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BarcodeQRCode;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author APRENDIZ
 */
public class registrarveh extends javax.swing.JFrame {

    /**
     * Creates new form registrarveh
     */
    public registrarveh() {
        initComponents();
        
         panel1.setBackground(new Color(255,251,251));
         this.setLocationRelativeTo(null);
        
        
        cj1.addKeyListener(new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
            String tipooo=tipoo2.getText();   
                
              
                    
                     if(cj1.getText().length()==7){
                    e.consume();
                
                }
                    if(cj1.getText().length()==3){
                        cj1.setText(cj1.getText()+"-");
                        
                      
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
               
            }
            
        });
        
        
        img1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                img1.setVisible(false);
              web_cam1.remove(img1);
            }

            @Override
            public void mousePressed(MouseEvent e) {
               
            }

            @Override
            public void mouseReleased(MouseEvent e) {
               
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                    Image img=getToolkit().getImage("src/Imagenes/tomar_foto2.png");
        img=img.getScaledInstance(img1.getWidth(),img1.getHeight(), Image.SCALE_DEFAULT);
        img1.setIcon(new ImageIcon(img));
       
            }

            @Override
            public void mouseExited(MouseEvent e) {
                        Image img=getToolkit().getImage("src/Imagenes/tomar_foto1.png");
        img=img.getScaledInstance(img1.getWidth(),img1.getHeight(), Image.SCALE_DEFAULT);
        img1.setIcon(new ImageIcon(img));
         
            }
        });
        
  
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tipoo = new javax.swing.JLabel();
        tipoo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cj1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cj2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        web_cam1 = new JPanelWebCam.JPanelWebCam();
        img1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Vehiculo");

        tipoo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        tipoo.setForeground(new java.awt.Color(255, 255, 255));
        tipoo.setText(".");

        tipoo2.setBackground(new java.awt.Color(0, 153, 153));
        tipoo2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        tipoo2.setForeground(new java.awt.Color(0, 153, 153));
        tipoo2.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 629, Short.MAX_VALUE)
                .addComponent(tipoo2)
                .addGap(191, 191, 191)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tipoo)
                    .addComponent(tipoo2))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 60));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Descripción");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        cj1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cj1ActionPerformed(evt);
            }
        });
        panel1.add(cj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Foto");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));

        cj2.setColumns(20);
        cj2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cj2.setLineWrap(true);
        cj2.setRows(5);
        cj2.setWrapStyleWord(true);
        jScrollPane1.setViewportView(cj2);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 500, 340));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("No.Placa");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("GUARDAR DATOS");
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 160, 40));

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("VERIFICAR EXISTENCIA");
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 190, 40));

        web_cam1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        web_cam1.setFONDO(true);
        web_cam1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                web_cam1MouseClicked(evt);
            }
        });

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tomar_foto1.png"))); // NOI18N
        img1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout web_cam1Layout = new javax.swing.GroupLayout(web_cam1);
        web_cam1.setLayout(web_cam1Layout);
        web_cam1Layout.setHorizontalGroup(
            web_cam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        web_cam1Layout.setVerticalGroup(
            web_cam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel1.add(web_cam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 340, 270));

        jLabel5.setText("(Click en el panel para tomar la foto)");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        
        Empleado e = new Empleado();
        e.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    public int rpta=0;

    
    
    public void verificar(){
        
        int tipove=Integer.parseInt(tipoo2.getText());
        try{
            
            String consulta="SELECT vehre_placa FROM vehiculos_registrados WHERE vehre_placa='"+cj1.getText()+"' and tipveh_cod='"+tipove+"'";
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);


while(rs.next())  {
    
    
    
    recorre+=1;
}          
            
        }catch(Exception ex){
            
            System.out.println(ex.getMessage());
            
        }
        
        
    }
    
    
    public int recorre=0;
   
    
    public void guardar_datos(){
        

int tipove=Integer.parseInt(tipoo2.getText());
try{
    
    Calendar fecha = new GregorianCalendar();
    
    int año = fecha.get(Calendar.YEAR);
    int mes = fecha.get(Calendar.MONTH);
    int dia = fecha.get(Calendar.DAY_OF_MONTH);
    byte[] imagen=web_cam1.getBytes();
   
 
    
    String fechaa=año+"-"+mes+"-"+dia;
    
    String consulta="INSERT INTO Vehiculos_registrados (tipveh_cod, vehre_placa, vehre_descrip, fecha_registro, vehre_foto) VALUES (?,?,?,?,?)";
    
    
    PreparedStatement ps=cn.prepareStatement(consulta);
    
    
    ps.setInt(1, tipove);
    ps.setString(2, cj1.getText());
    ps.setString(3,cj2.getText());
    ps.setString(4, fechaa);
    ps.setBytes(5, imagen);
    ps.executeUpdate();
    
    JOptionPane.showMessageDialog(null,"Datos registrados satisfactoriamente");
    
    
    
    
    
}catch(Exception ex){
    
    System.out.println(ex.getMessage());
    
}        



        
    }
    
    
    public void obtener_cod(){
        
        try{
            
            cod_veh=0;
            String consulta="SELECT vehre_cod FROM vehiculos_registrados WHERE vehre_placa='"+cj1.getText()+"'";
            
            Statement st =cn.createStatement();
            ResultSet rs = st.executeQuery(consulta);
            
            
            while(rs.next()){
                
                cod_veh=rs.getInt(1);
                
            }
            
            
        }catch(Exception ex){
            
            
            System.out.println(ex.getMessage());
        }        
        
        
        
    }
           
    public int cod_veh=0;
    
 
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      int tipove=Integer.parseInt(tipoo2.getText());
        
        if(cj1.getText().isEmpty()||cj2.getText().isEmpty()||(web_cam1.getBytes().length<=1)){
            
            
         JOptionPane.showMessageDialog(null,"Error"+ "\n"+ "Uno de los campos esta vacio", "FAIL", JOptionPane.ERROR_MESSAGE);

        }else{
            
            
          verificar();
       
       
       if(recorre>0){
           
           
           JOptionPane.showMessageDialog(null,"Error"+ "\n"+ "El vehiculo ya esta registrado en la base de datos", "FAIL", JOptionPane.ERROR_MESSAGE);
           
           recorre=0;
              
           if(tipove==2){
            
           vermotos vm = new vermotos();
           
           vm.b_placa.setText(cj1.getText());
           vm.setVisible(true);
           this.dispose();
           
               
           }else if(tipove==1){
                       
           verautos va = new verautos();
           va.b_placa.setText(cj1.getText());
           va.setVisible(true);
           this.dispose();
               
           }
            
           
           
       }else if(recorre==0){
           
           guardar_datos();
           
           if(tipove==2){
            
           vermotos vm = new vermotos();
           
           vm.b_placa.setText(cj1.getText());
           vm.setVisible(true);
           this.dispose();
           
               
           }else if(tipove==1){
                       
           verautos va = new verautos();
           va.b_placa.setText(cj1.getText());
           va.setVisible(true);
           this.dispose();
               
           }
               
          
       }
               }

       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cj1ActionPerformed
     
    }//GEN-LAST:event_cj1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     int tipove=Integer.parseInt(tipoo2.getText());  
     
     
     if(cj1.getText().isEmpty()){
         
         JOptionPane.showMessageDialog(null,"El campo esta vacio");
         
     }else{
         
       verificar();
       
if(recorre==0){
    
    JOptionPane.showMessageDialog(null,"El vehiculo no esta registrado");
    
    
}else if (recorre>0){
    
   
    
    recorre=0;
    
    
    if(tipove==2){
               
           vermotos vm = new vermotos();
           vm.b_placa.setText(cj1.getText());
           vm.setVisible(true);
           this.dispose();
           
               
           }else if(tipove==1){
             
           verautos va = new verautos();
           va.b_placa.setText(cj1.getText());
           va.setVisible(true);
           this.dispose();
               
           }
    
    
    
}
     }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void web_cam1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_web_cam1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_web_cam1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarveh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarveh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cj1;
    private javax.swing.JTextArea cj2;
    private javax.swing.JLabel img1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel1;
    public static volatile javax.swing.JLabel tipoo;
    public static volatile javax.swing.JLabel tipoo2;
    private JPanelWebCam.JPanelWebCam web_cam1;
    // End of variables declaration//GEN-END:variables
conexion cc= new conexion();
Connection cn =cc.conexion2();


}
