/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tooparking.usuario;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import tooparking.usuario.conexion;
import tooparking.usuario.usuario;
import tooparking.usuario.verdatos;

/**
 *
 * @author Aprendiz
 */
public class registrarsalida extends javax.swing.JFrame {

    /**
     * Creates new form registrarsalida
     */
    public registrarsalida() {
        initComponents();
        
        
        cj1.requestFocus();
        this.setLocationRelativeTo(null);
        panel1.setBackground(new Color(255,251,251));
       cj1.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent de) {
               if(cj1.getText().length()==10){
                      cj1.setEnabled(false);
                      
                   verificar();
                   
                   if(recorre==1){
                       
                 
                       inserta_datos();
                         
                       
                       
                   }else if(recorre==0){
                       
                       usuario u = new usuario();
                       JOptionPane.showMessageDialog(null,"Error, ingresa el tiquete denuevo", "ERROR", JOptionPane.ERROR_MESSAGE);
                      cj1.setEnabled(true);
                      dispose();
                      u.setVisible(true);
                   }
                   
               }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
              
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
               
            }
           
           
           
       });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cj1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(627, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("INSERTE SU TIQUETE DE ENTRADA");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        cj1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        panel1.add(cj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 260, 50));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int hh=0;
    public int mm=0;
    public float total=0;
    public float total2=0;
    public float total3=0;
    public float total4=0;
    
    public void inserta_datos(){
        
        
        
       try{
           
           System.out.println("sdfsdfs");
           hh=0;
           mm=0;
            Calendar fecha = new GregorianCalendar();
            
            int hh2 = fecha.get(Calendar.HOUR_OF_DAY);
            int mm2 = fecha.get(Calendar.MINUTE);
            total=0;
            total2=0;
            total3=0;
            total4=0;
            
           verdatos verr= new verdatos();
           String consulta="select vehiculos_registrados.Vehre_placa, ticket_entrada.Vehre_cod, ticket_entrada.Ticken_horas, ticket_entrada.Ticken_minutos, vehiculos_registrados.Vehre_foto FROM ticket_entrada, vehiculos_registrados WHERE ticket_entrada.Vehre_cod=vehiculos_registrados.Vehre_cod and ticket_entrada.Ticken_cod='"+cj1.getText()+"'";
           
           
           Statement st= cn.createStatement();
           ResultSet rs = st.executeQuery(consulta);
           
           while(rs.next()){
               
               hh=rs.getInt(3);
               System.out.println(""+hh);
               mm=rs.getInt(4);
               System.out.println(""+mm);
               
               
               verr.plaquita1.setText(rs.getString(1));
               Blob bl =rs.getBlob(5);
        byte[] data=bl.getBytes(1,(int) bl.length());
        BufferedImage imfg = null;
        
        imfg=ImageIO.read(new ByteArrayInputStream(data));
        
        ImageIcon icono= new ImageIcon(imfg);
        Icon icco=new ImageIcon(icono.getImage().getScaledInstance(verr.imagg.getWidth(), verr.imagg.getHeight(), Image.SCALE_DEFAULT));
        verr.imagg.setIcon(icco);
        verr.horae.setText(rs.getInt(3)+":"+rs.getInt(4)+":"+"00");
        verr.horaa.setText(hh2+":"+mm2+":"+"00");
        hh=rs.getInt(3);
        mm=rs.getInt(4);
        
        if(hh2==hh){
               
               total=mm2-mm;
               total2=total*50;
               verr.total.setText(""+total2);
               
               
           }else if(hh2>hh&&mm2>mm){
               
               
               total=hh2-hh;
               total2=mm2-mm;
               total3=total*60;
               total4=(total2+total3)*50;
               verr.total.setText(""+total4);
               
           }else if(hh2>hh&&mm>mm2){
               total=hh2-hh;
               
               
               if(total>1){
               
               total2=total*60;
           }
               for (int tt=mm;tt<60;tt++){
                   total3+=1;
                   
               }
               
               total4=(total3+mm2+total2)*50;
               verr.total.setText(""+total4);
               System.out.println(""+total4);
               
           }
        System.out.println(""+rs.getString(1));
        this.dispose();
        verr.jijox.setText(cj1.getText());
         verr.setVisible(true);  
               
           }
           
           
          
           
       }catch(Exception ex){
           
           System.out.println(ex.getMessage());
           
       } 
        
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
public int recorre=0;


public void verificar(){
    
    try{
        
        
        recorre=0;
        

        
    String consulta="select ticket_entrada.Ticken_cod FROM ticket_entrada where ticket_entrada.Ticken_cod='"+cj1.getText()+"'";
    
    
    Statement st =cn.createStatement();
    ResultSet rs =st.executeQuery(consulta);
    
    
    while(rs.next()){
        
        
        recorre+=1;
    }
        
    }catch(Exception ex){
        
        
        
        
    }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarsalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarsalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarsalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarsalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarsalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cj1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
conexion cc= new conexion();
Connection cn =cc.conexion2();


}
